update

diff --git a/compile b/compile
--- a/compile
+++ b/compile
@@ -3,21 +3,48 @@
 RED='\033[0;31m\033[1m'
 NC='\033[0m' # No Color
 
+function iferrorcomp () {
+    if [[ error -eq 1 ]]; then
+        printf "$RED\nCrit: ERROR had occured during compile!!\n"
+    fi
+}
+
+if [[ ! -f $1 || ! $1 && ! -f Makefile ]]; then
+    printf "$RED No file/arguments given.\n"
+    exit 1
+fi
+
 if [[ ${1##*.} == "asm" ]]; then
     printf "\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o\n"
-    nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o
+    nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o || error=1
+    if [[ error -eq 1 ]]; then
+        printf "\n\$ nasm -f elf64 -g -F dwarf $1 -; ${1%.*}.lst -o ${1%.*}.o: $RED\error had occured\n"
+        exit 1
+    fi
     printf "compiled into ${1%.*}.o\n"
-    printf "\$ ld ${1%.*}.o -o ${1%.*}"
+    printf "\$ ld ${1%.*}.o -o ${1%.*}" || error=1
+    if [[ error -eq 1 ]]; then
+        printf "\n\$ ld ${1%.*}.o -o ${1%.*}" || error=1
+        exit 1
+    fi
     ld ${1%.*}.o -o ${1%.*}
     printf "linked into ${1%.*}\n"
     printf "compiled into executable"
 elif [[ ${1##*.} == "c" || ${1##*.} == "cc" ]]; then
     printf "\$ gcc $1 -o ${1%.*}\n"
-    gcc $1 -o ${1%.*}
+    gcc $1 -o ${1%.*} || error=1
+    if [[ error -eq 1 ]]; then
+        printf "\n\$ gcc $1 -o ${1%.*}: $RED\error had occured\n"
+        exit 1
+    fi
     printf "compiled into ${1%.*}\n"
 elif [[ ${1##*.} == "cpp" ]]; then
     printf "\$ g++ $1 -o ${1%.*}\n"
-    g++ $1 -o ${1%.*}
+    g++ $1 -o ${1%.*} || error=1
+    if [[ error -eq 1 ]]; then
+        printf "\n\$ g++ $1 -o ${1%.*}: $RED\error had occured\n"
+        exit 1
+    fi
     printf "compiled into ${1%.*}\n"
 elif [[ ${1##*.} == "go" ]]; then
     printf "\$ go build $1\n"
diff --git a/compilerun b/compilerun
--- a/compilerun
+++ b/compilerun
@@ -10,19 +10,23 @@ function iferrorcomp ()
         exit 1
     fi
 }
+if [[ ! -f $1 || ! $1 && ! -f Makefile ]]; then
+    printf "$RED No file/arguments given.\n"
+    exit 1
+fi
 
 if [[ ${1##*.} == "asm" ]]; then
     printf "\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o\n"
     nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o || error=1
     if [[ error -eq 1 ]]; then
-        printf "\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o: $RED\error had occured\n"
+        printf "\n\$ nasm -f elf64 -g -F dwarf $1 -l ${1%.*}.lst -o ${1%.*}.o: $RED\error had occured\n"
         exit 1
     fi
     printf "compiled into ${1%.*}.o\n"
     printf "\$ ld ${1%.*}.o -o ${1%.*}\n"
     ld ${1%.*}.o -o ${1%.*} || error=1
     if [[ error -eq 1 ]]; then
-        printf "\$ ld ${1%.*}.o -o ${1%.*}: $RED\error had occured\n"
+        printf "\n\$ ld ${1%.*}.o -o ${1%.*}: $RED\error had occured\n"
         exit 1
     fi
     printf "linked into ${1%.*}\n"
@@ -33,7 +37,7 @@ elif [[ ${1##*.} == "c" || ${1##*.} == "cc" ]]; then
     printf "\$ gcc $1 -o ${1%.*}\n"
     gcc $1 -o ${1%.*} || error=1
     if [[ error -eq 1 ]]; then
-        printf "\$ gcc $1 -o ${1%.*}: $RED\error had occured\n"
+        printf "\n\$ gcc $1 -o ${1%.*}: $RED\error had occured\n"
         exit 1
     fi
     printf "compiled into ${1%.*}\n"
@@ -43,7 +47,7 @@ elif [[ ${1##*.} == "cpp" ]]; then
     printf "\$ g++ $1 -o ${1%.*}\n"
     g++ $1 -o ${1%.*} || error=1
     if [[ error -eq 1 ]]; then
-        printf "\$ g++ $1 -o ${1%.*}: $RED\error had occured\n"
+        printf "\n\$ g++ $1 -o ${1%.*}: $RED\error had occured\n"
         exit 1
     fi
     printf "compiled into ${1%.*}\n"
@@ -53,7 +57,7 @@ elif [[ ${1##*.} == "go" ]]; then
     printf "\$ go build $1\n"
     go build $1
     if [[ error -eq 1 ]]; then
-        printf "$RED\Crit: ERROR had occured during build!!\n"
+        printf "\n$RED\Crit: ERROR had occured during build!!\n"
         exit 1
     fi
     printf "compiled\n"
